TRUNCATE TABLE
  "role_permissions",
  "user_role_assignments",
  "permissions",
  "roles",
  "team_members",
  "entrees_main_courante",
  "types_evenement",
  "teams",
  "users",
  "sites",
  "tenant_api_keys",
  "tenant_invitations",
  "tenant_onboarding_checklists",
  "tenant_retention_policies",
  "tenant_quotas",
  "tenant_feature_flags",
  "tenant_sso_providers",
  "impersonation_sessions",
  "audit_logs",
  "archived_entries",
  "backup_runs",
  "tenants"
RESTART IDENTITY CASCADE;
